invoice/services/base.py
invoice/services/invoice.py
invoice/tests/services/invoice.py
invoice/validation/invoice.py

Require changes from https://github.com/openimis/openimis-be-invoice_py/pull/5
Ticket: [OPL-12](https://openimis.atlassian.net/browse/OPL-12)

 OPL-12: Added invoice match items 7505cca 

---

invoice/signals.py
invoice/tests/gql/invoice_line_item_schema.py
invoice/tests/gql/invoice_payment_schema.py
invoice/tests/helpers/default_test_data.py

TICKET: https://openimis.atlassian.net/browse/OPL-31

OPL-31: improve saving invoices in db

---

invoice/gql/bill/query.py
invoice/gql/gql_types/bill_types.py
invoice/gql/gql_types/invoice_types.py
invoice/gql/invoice/query.py
invoice/gql/invoice_line_item/query.py
invoice/utils.py

Ticket: https://openimis.atlassian.net/browse/OPL-40
changes to support filtering via Type.

OPL-40: added adjustments for graphQL with GenericTypes

---

invoice/gql/gql_types/invoice_types.py

Change requested by @rstencel for Family subjectType.

OPL-40: changes to show Family projection in graphQL

---

invoice/gql/filter_mixin.py

part of TICKET:  https://openimis.atlassian.net/browse/OPL-47 - missing filters

OPL-47: added missing filters

---

invoice/gql/bill_item/query.py
invoice/gql/gql_types/bill_types.py
invoice/migrations/0004_invoice_bill_roles_for_admin.py
invoice/migrations/0005_invoice_bill_roles_for_accountant.py

TICKET: https://openimis.atlassian.net/browse/OPL-32

OPL-32: Add all invoices/bill right to "IMIS administrator" and "accountant" roles

---

invoice/gql/bill_item/query.py
invoice/gql/gql_types/bill_types.py

Part of TICKET: https://openimis.atlassian.net/browse/OPL-66

OPL-66: changes required to have BillItem and BarchRun SubjectType working

---

invoice/services/invoice.py
invoice/signals.py

[https://openimis.atlassian.net/browse/OPL-68](https://openimis.atlassian.net/browse/OPL-68)
Changes:
- Moved `save_invoice_in_db` to `InvoiceService` as `invoice_create` to allow signal binding. (Similar to the solution used in `BillService`)

OPL-68 Add signal bindings for Subscription handling

---

invoice/services/__init__.py
invoice/services/paymentInvoice.py

part of TICKET: https://openimis.atlassian.net/browse/OP-503
this will be required to have fhir test working in main PR of this ticket

OP-503: added service for adding payment with detail for PaymentNotice endpoint

---

invoice/services/paymentInvoice.py

part TICKET: https://openimis.atlassian.net/browse/OP-779
added signals for payment services.

OP-779: added signal after updating payment invoices status

---

invoice/migrations/0004_invoice_bill_roles_for_admin.py
invoice/migrations/0005_invoice_bill_roles_for_accountant.py

More portable and a lot shorter 😀

PostgreSQL support

---

invoice/tests/__init__.py
invoice/tests/gql/base.py
invoice/tests/helpers/default_test_data.py
invoice/tests/services/invoice.py
invoice/tests/services/invoiceLineItem.py
invoice/tests/services/invoicePayment.py
invoice/tests/services/paymentInvoice.py

[https://openimis.atlassian.net/browse/OP-868](https://openimis.atlassian.net/browse/OP-868)
Changes:
- Changed handling of JSON fields from JSON strings to python dictionaties (Django 3.2 update)
- Fixed TestCase handling (added all missing calls to super.setUpClass, super.setUp, removed unecessary teardowns)
- Removed some unused code/comments/imports
- Fixed code formatting

OP-868 Fix CI issues caused by Django 3.2 update

---

invoice/gql/bill/query.py
invoice/models.py

TICKET: [OTC-734](https://openimis.atlassian.net/browse/OTC-734)

OTC:734: Added export

---

.github/workflows/openmis-module-test.yml
invoice/gql/gql_types/bill_types.py
invoice/gql/gql_types/invoice_types.py
invoice/gql/gql_types/payment_types.py

https://openimis.atlassian.net/browse/OTC-878

OTC-878: add all permission to gql mutations and queries

---

.github/workflows/openmis-module-test.yml
invoice/gql/gql_types/bill_types.py
invoice/gql/gql_types/invoice_types.py
invoice/gql/gql_types/payment_types.py

MERGING RELEASE branches
Release release/23.04

MERGING RELEASE branches

---

.github/workflows/openmis-module-test.yml
sonar-project.properties

Sonar configuration and coverage for backend invoice module

ISE-183: sonar configuration

---

invoice/gql/detail_payment_invoice/mutation.py
invoice/gql/payment_invoice/mutation.py

[https://openimis.atlassian.net/browse/CM-188](https://openimis.atlassian.net/browse/CM-188)

CM-188 Adjusted backend for social protection

---

invoice/tests/gql/detail_payment_invoice_schema.py
invoice/tests/gql/invoice_line_item_schema.py
invoice/tests/gql/payment_invoice_schema.py

https://openimis.atlassian.net/browse/OP-1523
This PR fixes test in invoice module.

OP-1523: fix tests for invoice

---

invoice/gql/bill/query.py
invoice/tests/gql/invoice_line_item_schema.py

[https://openimis.atlassian.net/browse/OP-1500](https://openimis.atlassian.net/browse/OP-1500)

OP-1500 Backend CI are not working

---

invoice/apps.py

https://openimis.atlassian.net/browse/OP-1518
This PR changes the way how config is loaded.

OP-1518: change how cofing is loaded

---

invoice/services/bill.py

[https://openimis.atlassian.net/browse/OM-127](https://openimis.atlassian.net/browse/OM-127)

OM-127 Changed floats to decimals in bill_create service method

---

invoice/gql/gql_types/bill_types.py
invoice/gql/gql_types/invoice_types.py

[https://openimis.atlassian.net/browse/OM-137](https://openimis.atlassian.net/browse/OM-137)

OM-137 Fixed subject, third party and line resolvers

---

invoice/apps.py
invoice/gql/bill/query.py
invoice/gql/invoice/query.py

[https://openimis.atlassian.net/browse/OM-139](https://openimis.atlassian.net/browse/OM-139l)

OM-139 Implement bill/invoice generic hookable user filter

---

invoice/gql/bill_event/query.py
invoice/gql/bill_item/query.py
invoice/gql/bill_payment/query.py
invoice/gql/invoice_event/query.py
invoice/gql/invoice_line_item/query.py
invoice/gql/invoice_payment/query.py

[https://openimis.atlassian.net/browse/OM-144](https://openimis.atlassian.net/browse/OM-144)

OM-144 added user filters for bill/invoice line/payments/events

---

invoice/gql/bill_event/query.py
invoice/gql/bill_item/query.py
invoice/gql/bill_payment/query.py
invoice/gql/invoice_event/query.py
invoice/gql/invoice_line_item/query.py
invoice/gql/invoice_payment/query.py

MERGING develop into release/24.04

MERGING develop into release/24.04
